# Dependencies
markdown:         kramdown
highlighter:      pygments
gems:
- jekyll-gist
- jekyll-paginate

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Lincoln Swaine-Moore
tagline:          'Personal Website'
description:      "Yale Computer Science Class of 2017"
url:              http://lswainemoore.github.io
baseurl:          /

author:
  name:           'Lincoln Swaine-Moore'
  url:            http://lswainemoore.com

paginate:         5

# Custom vars
version:          -0.1.0

github:
  repo:           https://github.com/lswainemoore

email_address:    lswainemoore@gmail.com
twitter_username: lswainemoore
github_username:  lswainemoore
linkedin_username: lincoln-swaine-moore-0463a474
